apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-test
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: gh-test
  template:
    metadata:
      labels:
        app: gh-test
    spec:
      containers:


      - name: gh-test
        image: devopsaes/ghatestakif:37
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
