apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-test
spec:
  replcas: 2
  selector:
    matchLabels:
      app: gh-test
  template:
    metadata:
      labels:
        app: gh-test
    spec:
      containers:

      - name: gh_test
        image: devopsaes/ghatestakif:30


