name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Get build info (build number, commit ID, and date)
      - name:  docker build
        run: docker build -t ${{ vars.DOCKERHUB_UNAME }}/${{ vars.DOCKERHUB_APPNAME }}:${{ github.run_number }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_UNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: docker push
        run: docker push ${{ vars.DOCKERHUB_UNAME }}/${{ vars.DOCKERHUB_APPNAME }}:${{ github.run_number }}
         

      - name: update manifest file
        run: sed -i 's/${{ vars.DOCKERHUB_APPNAME }}.*/${{ vars.DOCKERHUB_APPNAME }}:${{ github.run_number }}/g' ./k8s/deployment.yaml


      - name: Commit and push updated deployment file
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add ./k8s/deployment.yaml
          git commit -m "Update deployment.yaml with new Docker image tag ${GITHUB_RUN_NUMBER}"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}