name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Get build info (build number, commit ID, and date)
      - name:  docker build
        run: docker build -t ${{ vars.DOCKERHUB_UNAME }}/${{ vars.DOCKERHUB_APPNAME }}:${{ github.run_number }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_UNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: docker push
        run: docker push ${{ vars.DOCKERHUB_UNAME }}/${{ vars.DOCKERHUB_APPNAME }}:${{ github.run_number }}
         

      - name: update manifest file
        run: sed -i 's/${{ vars.DOCKERHUB_APPNAME }}.*/${{ vars.DOCKERHUB_APPNAME }}:${{ github.run_number }}/g' ./k8s/deployment.yaml

      - name: Commit updated Kubernetes YAML
        run: |
          git config --local user.name "aesakif"
          git config --local user.email "akif@anwargroup.com"
          git add ./k8s
          git commit -m "Update image tag to ${{ github.run_number }}"
          git push https://${{ secrets.GH_TOKEN }}@github.com/aesakif/actions