name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Get build info (build number, commit ID, and date)
      - name:  get-info
        run: docker build -t ${{ vars.DOCKERHUB_APPNAME }}:${{ github.run_number }} .
      - name: list images
        run: docker images 
         