name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

  list:
    needs: clone
    runs-on: ubuntu-latest
    steps:
      # Step 1: List the contents of the directory
      - name: List Directory Contents
        run: ls -ltra
