name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  clone:
    runs-on: ubuntu-latest
    outputs:
      build-number: ${{ steps.get-info.outputs.build_number }}
      commit-id: ${{ steps.get-info.outputs.commit_id }}
      commit-date: ${{ steps.get-info.outputs.commit_date }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
